// gh2test - ReXGlue Recompiled Project
// Generated by: rexglue init
//
// This file is SDK-managed. Customizations go in virtual hook overrides.
// Running 'rexglue migrate' will overwrite this file.

#include "generated/gh2test_config.h"
#include "generated/gh2test_init.h"

#include <rex/rex_app.h>

#include "rex/ppc/function.h"

class Gh2testApp : public rex::ReXApp {
 public:
  using rex::ReXApp::ReXApp;

  static std::unique_ptr<rex::ui::WindowedApp> Create(
      rex::ui::WindowedAppContext& ctx) {
    return std::unique_ptr<Gh2testApp>(new Gh2testApp(ctx, "gh2test",
        {PPC_CODE_BASE, PPC_CODE_SIZE, PPC_IMAGE_BASE,
         PPC_IMAGE_SIZE, PPCFuncMappings}));
  }
};

REX_DEFINE_APP(gh2test, Gh2testApp::Create)

PPC_HOOK(rex_sub_8239CA70, memset)
PPC_HOOK(rex_sub_8239CB70, memcpy)
PPC_HOOK(rex_sub_8239D4F0, memmove)
PPC_STUB(__imp__XamShowGamerCardUIForXUID)
PPC_STUB(__imp__XamShowMarketplaceUI)
PPC_STUB(__imp__XamUserCreateStatsEnumerator)
PPC_STUB(__imp__NetDll_getsockname)
PPC_STUB(__imp__NetDll_getpeername)
